"""Initial migration

Revision ID: 571f57af7e57
Revises: 
Create Date: 2024-08-28 15:29:59.068174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '571f57af7e57'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OG_LEASE_CYCLE',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('OIL_GAS_CODE', sa.CHAR(length=1), nullable=False),
    sa.Column('DISTRICT_NO', sa.CHAR(length=2), nullable=False),
    sa.Column('LEASE_NO', sa.String(length=6), nullable=False),
    sa.Column('CYCLE_YEAR', sa.CHAR(length=4), nullable=False),
    sa.Column('CYCLE_MONTH', sa.CHAR(length=2), nullable=False),
    sa.Column('CYCLE_YEAR_MONTH', sa.String(length=6), nullable=True),
    sa.Column('LEASE_NO_DISTRICT_NO', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('OPERATOR_NO', sa.String(length=6), nullable=True),
    sa.Column('FIELD_NO', sa.String(length=8), nullable=True),
    sa.Column('FIELD_TYPE', sa.CHAR(length=2), nullable=True),
    sa.Column('GAS_WELL_NO', sa.String(length=6), nullable=True),
    sa.Column('PROD_REPORT_FILED_FLAG', sa.CHAR(length=1), nullable=True),
    sa.Column('LEASE_OIL_PROD_VOL', sa.Numeric(precision=9, scale=0), nullable=True),
    sa.Column('LEASE_OIL_ALLOW', sa.Numeric(precision=9, scale=0), nullable=True),
    sa.Column('LEASE_OIL_ENDING_BAL', sa.Numeric(precision=9, scale=0), nullable=True),
    sa.Column('LEASE_GAS_PROD_VOL', sa.Numeric(precision=9, scale=0), nullable=True),
    sa.Column('LEASE_GAS_ALLOW', sa.Numeric(precision=9, scale=0), nullable=True),
    sa.Column('LEASE_GAS_LIFT_INJ_VOL', sa.Numeric(precision=9, scale=0), nullable=True),
    sa.Column('LEASE_COND_PROD_VOL', sa.Numeric(precision=9, scale=0), nullable=True),
    sa.Column('LEASE_COND_LIMIT', sa.Numeric(precision=9, scale=0), nullable=True),
    sa.Column('LEASE_COND_ENDING_BAL', sa.Numeric(precision=9, scale=0), nullable=True),
    sa.Column('LEASE_CSGD_PROD_VOL', sa.Numeric(precision=9, scale=0), nullable=True),
    sa.Column('LEASE_CSGD_LIMIT', sa.Numeric(precision=9, scale=0), nullable=True),
    sa.Column('LEASE_CSGD_GAS_LIFT', sa.Numeric(precision=9, scale=0), nullable=True),
    sa.Column('LEASE_OIL_TOT_DISP', sa.Numeric(precision=9, scale=0), nullable=True),
    sa.Column('LEASE_GAS_TOT_DISP', sa.Numeric(precision=9, scale=0), nullable=True),
    sa.Column('LEASE_COND_TOT_DISP', sa.Numeric(precision=9, scale=0), nullable=True),
    sa.Column('LEASE_CSGD_TOT_DISP', sa.Numeric(precision=9, scale=0), nullable=True),
    sa.Column('DISTRICT_NAME', sa.CHAR(length=2), nullable=True),
    sa.Column('LEASE_NAME', sa.String(length=255), nullable=True),
    sa.Column('OPERATOR_NAME', sa.String(length=50), nullable=True),
    sa.Column('FIELD_NAME', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('OG_WELL_COMPLETION',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('OIL_GAS_CODE', sa.CHAR(length=1), nullable=False),
    sa.Column('DISTRICT_NO', sa.CHAR(length=2), nullable=False),
    sa.Column('LEASE_NO', sa.String(length=6), nullable=False),
    sa.Column('WELL_NO', sa.String(length=6), nullable=False),
    sa.Column('API_COUNTY_CODE', sa.CHAR(length=3), nullable=False),
    sa.Column('API_UNIQUE_NO', sa.String(length=5), nullable=False),
    sa.Column('ONSHORE_ASSC_CNTY', sa.CHAR(length=3), nullable=True),
    sa.Column('DISTRICT_NAME', sa.CHAR(length=2), nullable=True),
    sa.Column('COUNTY_NAME', sa.String(length=50), nullable=True),
    sa.Column('OIL_WELL_UNIT_NO', sa.String(length=6), nullable=True),
    sa.Column('WELL_ROOT_NO', sa.String(length=8), nullable=True),
    sa.Column('WELLBORE_SHUTIN_DT', sa.String(length=6), nullable=True),
    sa.Column('WELL_SHUTIN_DT', sa.String(length=6), nullable=True),
    sa.Column('WELL_14B2_STATUS_CODE', sa.CHAR(length=1), nullable=True),
    sa.Column('WELL_SUBJECT_14B2_FLAG', sa.CHAR(length=1), nullable=True),
    sa.Column('WELLBORE_LOCATION_CODE', sa.CHAR(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('og_lease_cycle')
    op.drop_table('og_well_completion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('og_well_completion',
    sa.Column('oil_gas_code', sa.CHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('district_no', sa.CHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('lease_no', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('well_no', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('api_county_code', sa.CHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('api_unique_no', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('onshore_assc_cnty', sa.CHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('district_name', sa.CHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('county_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('oil_well_unit_no', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('well_root_no', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('wellbore_shutin_dt', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('well_shutin_dt', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('well_14b2_status_code', sa.CHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('well_subject_14b2_flag', sa.CHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('wellbore_location_code', sa.CHAR(length=1), autoincrement=False, nullable=True)
    )
    op.create_table('og_lease_cycle',
    sa.Column('oil_gas_code', sa.CHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('district_no', sa.CHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('lease_no', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('cycle_year', sa.CHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('cycle_month', sa.CHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('cycle_year_month', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('lease_no_district_no', sa.NUMERIC(precision=10, scale=0), autoincrement=False, nullable=True),
    sa.Column('operator_no', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('field_no', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('field_type', sa.CHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('gas_well_no', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('prod_report_filed_flag', sa.CHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('lease_oil_prod_vol', sa.NUMERIC(precision=9, scale=0), autoincrement=False, nullable=True),
    sa.Column('lease_oil_allow', sa.NUMERIC(precision=9, scale=0), autoincrement=False, nullable=True),
    sa.Column('lease_oil_ending_bal', sa.NUMERIC(precision=9, scale=0), autoincrement=False, nullable=True),
    sa.Column('lease_gas_prod_vol', sa.NUMERIC(precision=9, scale=0), autoincrement=False, nullable=True),
    sa.Column('lease_gas_allow', sa.NUMERIC(precision=9, scale=0), autoincrement=False, nullable=True),
    sa.Column('lease_gas_lift_inj_vol', sa.NUMERIC(precision=9, scale=0), autoincrement=False, nullable=True),
    sa.Column('lease_cond_prod_vol', sa.NUMERIC(precision=9, scale=0), autoincrement=False, nullable=True),
    sa.Column('lease_cond_limit', sa.NUMERIC(precision=9, scale=0), autoincrement=False, nullable=True),
    sa.Column('lease_cond_ending_bal', sa.NUMERIC(precision=9, scale=0), autoincrement=False, nullable=True),
    sa.Column('lease_csgd_prod_vol', sa.NUMERIC(precision=9, scale=0), autoincrement=False, nullable=True),
    sa.Column('lease_csgd_limit', sa.NUMERIC(precision=9, scale=0), autoincrement=False, nullable=True),
    sa.Column('lease_csgd_gas_lift', sa.NUMERIC(precision=9, scale=0), autoincrement=False, nullable=True),
    sa.Column('lease_oil_tot_disp', sa.NUMERIC(precision=9, scale=0), autoincrement=False, nullable=True),
    sa.Column('lease_gas_tot_disp', sa.NUMERIC(precision=9, scale=0), autoincrement=False, nullable=True),
    sa.Column('lease_cond_tot_disp', sa.NUMERIC(precision=9, scale=0), autoincrement=False, nullable=True),
    sa.Column('lease_csgd_tot_disp', sa.NUMERIC(precision=9, scale=0), autoincrement=False, nullable=True),
    sa.Column('district_name', sa.CHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('lease_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('operator_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('field_name', sa.VARCHAR(length=32), autoincrement=False, nullable=True)
    )
    op.drop_table('OG_WELL_COMPLETION')
    op.drop_table('OG_LEASE_CYCLE')
    # ### end Alembic commands ###
